### PR TITLE
Add app-launchbar and app-slaunch to the repository.

### PR DESCRIPTION
**Pull request by XeonSquared**
Just a PR for the two launchers I wrote recently. Both are public-domain like the rest of the repo.

### CODE REVIEW

**Comment by 20kdc** [comment]
Everything is mostly in order, though you should probably add authorship information to your Lua files, and add the license to the dependencies to ensure the "Public Domain" license file gets downloaded.

**Comment by XeonSquared** [comment]
That should fix those issues up.

**Comment by 20kdc** [comment]
The quick revision to README.md only affects code/ stuff, of which there is none, so ready to merge when you are.

**Comment by 20kdc** [comment]
```
<t20kdc> PR acceptable, ready when you are
<Izaya> all good whenever
```
---
Treating as confirmation, merging.

**Pull request merged**
